services:

  music_db:
    image: postgres:13
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music_user -d music_db"]
      interval: 20s
      timeout: 10s
      retries: 3


  microservice-music:
    build:
      context: ../services/music
    container_name: vistor-service-music
    ports:
      - "8000:8000"
    environment:
      # - DATABASE_URL=postgresql+asyncpg://music_user:music_password@music_db:5431/music_db
      - DATABASE_URL=sqlite+aiosqlite:///./app.db
      - POSTGRES_HOST=music_db
      - POSTGRES_PORT=5431
    depends_on:
      music_db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      # - ../microservices/music/app:/app  # Application code
      - /mnt/games/Music:/app/music  # Music directory

networks:
  default:
    driver: bridge

volumes:
  pg_data:
