services:

  microservice-nyaa:
    build:
      context: ../microservices/nyaa
    container_name: vistor-microservice-nyaa
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
  microservice-anilist:
    build:
      context: ../microservices/anilist
    container_name: vistor-microservice-anilist
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
  microservice-music:
    build:
      context: ../microservices/music
    container_name: vistor-microservice-music
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - /mnt/games/Music:/app/music  # Music directory
