services:

  microservice-music:
    build:
      context: ../microservices/music
    container_name: vistor-microservice-music
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - /mnt/games/Music:/app/music  # Music directory

networks:
  default:
    driver: bridge
